### ISSUE TITLE
执行npm run dev时报错

### ISSUE THREAD

**Issue by rovertang** [hbstack/theme#1034]
npm run dev

> dev
> hugo server --gc --enableGitInfo -D

Watching for changes in C:\Web\hbstacktest\blog\{archetypes,assets,content,layouts,package.json}
Watching for config changes in C:\Web\hbstacktest\blog\config\_default, C:\RoverWeb\hbstacktest\blog\config\development, C:\Web\hbstacktest\blog\go.mod
Start building sites …
hugo v0.136.0-2939270a3bb78b3799973345c0dab7fa239cef9d+extended windows/amd64 BuildDate=2024-10-15T13:17:24Z VendorInfo=gohugoio

ERROR TOCSS-DART: failed to transform "hb/scss/index.scss" (text/x-scss): "<stream>:1:1": failed to write payload: write |1: The pipe has been ended.
Built in 5479 ms
Error: error building site: TOCSS-DART: failed to transform "hb/scss/index.scss" (text/x-scss): "<stream>:1:1": connection is shut down

**Comment by razonyang** [comment]
> Error: error building site: TOCSS-DART: failed to transform "hb/scss/index.scss" (text/x-scss): ":1:1": connection is shut down

看起来像似安装了 Node.js 版的 Sass，然而该版本不支持 Embeded 协议，卸载 Node.js 版后，按照[文档](https://gohugo.io/hugo-pipes/transpile-sass-to-css/#installing-in-a-development-environment)重新安装 Dart Sass。

**Comment by rovertang** [comment]
我的sass是通过npm install的。卸载以后，使用上述文档中的方法进行安装，当前已可以编译。谢谢
