### ISSUE TITLE
How to install Dart Sass using Docker image?

### ISSUE THREAD

**Issue by gavlinski** [hbstack/theme#1059]
Hi!

I have a similar problem described in #1034, but I'm using Docker to build and test changes using my local machine. I've upgraded all modules to last versions using `hugo mod get -u` and then migrate hugomods from "hugo:0.124.1" to "hugo:0.138.0".

How can I install Dart Sass and fix the error below? Should I use another image tag? Any tips will be appreciated.

```terminal
$ docker run --rm -v $(pwd):/src -v $(pwd):/modules -e HUGO_CACHEDIR="/modules" -p 1313:1313 hugomods/hugo:0.138.0 hugo server --bind 0.0.0.0 --buildDrafts
Watching for changes in /src/{archetypes,assets,content,data,i18n,layouts,package.json}
Watching for config changes in /src/config/_default, /src/config/development, /src/go.mod
Start building sites … 
hugo v0.138.0-ad82998d54b3f9f8c2741b67356813b55b3134b9+extended linux/amd64 BuildDate=2024-11-06T11:22:34Z VendorInfo=hugomods

Built in 1975 ms
Error: error building site: TOCSS-DART: failed to transform "hb/scss/index.scss" (text/x-scss). You need to install Dart Sass, see https://gohugo.io//functions/css/sass/#dart-sass: this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
```
```terminal
$ docker run --rm -v $(pwd):/src -v $(pwd):/modules -e HUGO_CACHEDIR="/modules" -p 1313:1313 hugomods/hugo:0.138.0 hugo env
hugo v0.138.0-ad82998d54b3f9f8c2741b67356813b55b3134b9+extended linux/amd64 BuildDate=2024-11-06T11:22:34Z VendorInfo=hugomods
GOOS="linux"
GOARCH="amd64"
GOVERSION="go1.23.2"
github.com/sass/libsass="3.6.6"
github.com/webmproject/libwebp="v1.3.2"
```

**Comment by razonyang** [comment]
Hi, I suggest using the `hugomods/hugo:dart-sass` or `hugomods/hugo:exts` tag.

BTW, there are `non-root` tags available now, to use it by appending the `-non-root` into the tag, such as `hugomods/hugo:exts-non-root` or `hugomods/hugo:exts-non-root-<version>` for particular version.

Moreover, if you require the Hugo deploy feature (`hugo deploy`), you'll need to use the `ci*` tags.

Here is a page to [Choose a Hugo Docker image](https://docker.hugomods.com/choose/).

**Comment by razonyang** [comment]
> However, some warnings were displayed as follows:

Upgrade bootstrap to `main` branch should have less warning, but there are still deprecated warnings present, see also https://github.com/twbs/bootstrap/issues/40849.

```sh
hugo mod get github.com/twbs/bootstrap@main
```

> failed to acquire a build lock: open /src/.hugo_build.lock: permission denied".

You can try deleting the file and trying again.

In my experience, it works with `non-root` images after `chown` the owner to myself (`1000:1000`). There might be unexpected case I haven't thought about.

**Comment by razonyang** [comment]
You can also downgrade Docker image to `0.136.5` which `sass` version is 1.77.4.

**Comment by gavlinski** [comment]
Great! I was able to get it working with the `exts-non-root-0.136.5` image using [this tip](https://discourse.gohugo.io/t/hugo-docker-nginx-proxy-manager-docker-solved/47678/7).

These were the commands I needed to run:

```terminal
$ sudo chown -R myuser:domain\ users .
$ id -u
123456789
$ docker run --rm -v $(pwd):/src -v $(pwd):/modules -e \
  HUGO_CACHEDIR="/modules" -p 1313:1313 -u 123456789 \
  hugomods/hugo:exts-non-root-0.136.5 hugo server \
  --bind 0.0.0.0 --buildDrafts
```

Thank you very much for your valuable help! :heart:

**Comment by razonyang** [comment]
FYI, since [github.com/hbstack/hb@v0.16.0](https://github.com/hbstack/hb/releases/tag/v0.16.0) (requires Hugo's v0.139.2 or later), those warnings were ignored by default.
