### ISSUE TITLE
PWA minimal required configuration for the Starter Theme

### ISSUE THREAD

**Issue by gavlinski** [hbstack/theme#1074]
Hello!

[HB Starter Theme](https://theme.hbstack.dev/en/) should apparently come with pre-configured PWA support as we can see. However, when running it locally, the install button is not displayed in the browser. I tried to follow the tips on the website https://hugomods.com/docs/pwa/ but they are for those who do not use the theme. In the example repository https://github.com/hugomods/pwa/tree/main/exampleSite I found some additional configurations, but the files are in toml format instead of yaml.

Can you please help me make the necessary configurations? Or tell me if there is any secret to testing locally, such as some parameter when running the docker container with `hugo server`. One of the things I saw that was missing was adding an image to path `/assets/images/pwa/icon.png`.

**Comment by razonyang** [comment]
> However, when running it locally, the install button is not displayed in the browser.

Hi, I assume you've imported the [PWA installer](https://hbstack.dev/modules/enhancement/pwa-installer/) module, which is not imported into this template by default.

If the button doesn't pop up on the development environment, please:

1. Check if the PWA module is disabled on development, `hugopress.modules.pwa.disable` on [`config/development/params.yaml`](https://github.com/hbstack/theme/blob/main/config/development/params.yaml), which is `true` by default on this template, set it to `false` to debug.
2. Clear local storage on the browser, which may prevent the install button from appearing.

![image](https://github.com/user-attachments/assets/5b5547fa-9083-4469-a005-0f9d6d9d5bdb)

> One of the things I saw that was missing was adding an image to path /assets/images/pwa/icon.png.

The template's parameter should include minimal working template, and the `icon_path` was set as the logo one on https://github.com/hbstack/pwa/blob/f5c74a60c9374221feaa79d61fb3c8506c631268/hugo.toml#L8C1-L8C11, no need to specify unless the icon is different from the logo.

I tested the template with the following steps locally and it works.

1. Import the `github.com/hbstack/pwa-installer` module.
2. Set `hugopress.modules.pwa.disable` as `false` on `config/development/params.yaml`.

If it still doesn't work, please provide a minimal reproducible repo and the browser you're using, will check if it's a bug.

**Comment by razonyang** [comment]
BTW, there are two types of install buttons.

![image](https://github.com/user-attachments/assets/34ec822d-f16d-4775-ad3c-6db27d0b98db)

The first is based on the built-in browser UI, which varies between browsers.

The second one is powered by the [PWA installer](https://hbstack.dev/modules/enhancement/pwa-installer/) module,  it doesn't support FireFox and Safari.

**Comment by razonyang** [comment]
Hmm, one more thing to note is that the second type of install button won't pop up if you've installed the application (add site to homepage).

**Comment by gavlinski** [comment]
Thank you so much for the super detailed explanation with screenshots and examples! Setting the option `hugopress.modules.pwa.disable` on [`config/development/params.yaml`](https://github.com/hbstack/theme/blob/main/config/development/params.yaml) to `false` was enough to get the Chrome (v130.0.6723.116) built-in button to show up. The other steps were not necessary in this scenario.

> 1\. Check if the PWA module is disabled on development,

Done, solved the problem as I commented above.

> 2\. Clear local storage on the browser

I checked but these two properties did not exist, as I had never installed it before.

> The template's parameter should include minimal working template

I used the file [`config/_default/params.yaml`](https://github.com/hbstack/theme/blob/main/config/_default/params.yaml) from HB Starter Theme as a template, which does not come with the `icon_path` option defined, but maybe the default value is assumed, which is `images/pwa/icon.png`. So I just added the specified file to this path.

> 1\. Import the `github.com/hbstack/pwa-installer` module.

This step was not necessary to show the Chrome browser's built-in button.  
I will attach my [`config/_default/module.yaml`](https://github.com/hbstack/theme/blob/main/config/_default/module.yaml) and [`go.mod`](https://github.com/hbstack/theme/blob/main/go.mod) files for you to review, please see below.

> The second one is powered by the [PWA installer](https://hbstack.dev/modules/enhancement/pwa-installer/) module

In this case, yes, I think the previous step of importing `pwa-installer` additional module would be necessary.

---

[my_files.zip](https://github.com/user-attachments/files/18002272/my_files.zip)

**Comment by razonyang** [comment]
Yeah, the PWA installer module is not required for the browser's installer button. That module is used to pop up a prominent install button, which may be useful on mobile devices. 

I just added more parameters and comments for PWA on #1075.

Please close this issue if it has been resolved. Please let me know if I missed anything.

**Comment by gavlinski** [comment]
Looks great! Thank you again.

Issue closed as it's resolved.

**Comment by gavlinski** [comment]
Hi again!

Sorry for reopen this issue, but now I need to figure out how to show browser's installer button on **production** environment. It's working fine on development, but I can't make it working after deploy using GitLab Pages (internal access only for now). Is setting `HUGO_ENV: production` variable required? Maybe PWA it's not compatible with GitLab Pages?

Here is my .gitlab-ci.yml:

```yml
image: hugomods/hugo:exts-0.136.5

variables:
  GIT_SSL_NO_VERIFY: "true"
  GIT_SUBMODULE_STRATEGY: recursive
  HUGO_ENV: production

pages:  # a predefined job that builds your pages and saves them to the specified path.
  script:
    - hugo --minify --gc --enableGitInfo
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  environment: production
```

Any suggestions you have are welcome as always. Thanks!

**Comment by razonyang** [comment]
The steps to troubleshoot are as follows.

## 1. Ensure the website URL is secure.

The localhost and 127.0.0.1 are treated as secure, please check the public site URL is accessed via `https`.

## 2. Clear the browser's cache.

To ensure that the most recent service worker was registered correctly.

![image](https://github.com/user-attachments/assets/be24f584-9307-45d2-beb1-80f35b89531d)

## 3. Check the status of Manifest and Service workers.

Navigate to `Applioation` -> `Manifest`/`Service workers`, if there is an error, please post it here.

## 4. Check if there are errors on **Console**

Dev Tools -> Console tab.

## 5. Others

It may be challenging to debug. I would appreciate a reproducible demo and a URL to test if the steps above do not work.

What browser do you use?

**Comment by razonyang** [comment]
If you're using FireFox or Safari on desktops, there will no install button.

> Firefox and Safari do not support installing PWAs using a manifest file on desktops.
> https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Guides/Making_PWAs_installable#browser_support

**Comment by razonyang** [comment]
No problem, thank you for your supplementary explanation, it would be helpful for others.
