### ISSUE TITLE
Support for Plausible Analytics

### ISSUE THREAD

**Issue by Rubonnek** [hbstack/theme#136]
Is support for Plausible Analytics planned?

**Comment by razonyang** [comment]
Seems there is no free plan, I remember I've registered it before, but expired now.
Will try to self-host and see how it works.

**Comment by razonyang** [comment]
Done, see https://hugomods.com/en/docs/analytics/plausible/ for details.

BTW, you don't have to _Import the Script_ mentioned in the docs, since the HB framework is built on top of HugoPress.
