### ISSUE TITLE
Hugo content 

### ISSUE THREAD

**Issue by keybasegit** [hbstack/theme#21]
Following Hugo content guidelines https://gohugo.io/content-management/organization/ I copy 9 title.md files into docs folder. All files obey strictly Hugo rules about yaml and content.
  Files aren't recognised in hbs theme and I do realize that hbs theme content organisation means that for each and every page, article or doc.md I need to create folder with a name and index.md. 
  It will impede on using hbs theme as digital garden as I got 523 files under 202304091537-title.md (yearmonthdayhourminute-title.md).

**Comment by razonyang** [comment]
Could you provide details about how do you organize your content, I didn't reproduce this.

```
ls -al content/docs
total 48
drwxr-xr-x  4 razonyang razonyang 4096 Apr 10 04:24 .
drwxr-xr-x 11 razonyang razonyang 4096 Apr  6 01:55 ..
-rw-r--r--  1 razonyang razonyang   17 Apr 10 04:23 1.md
-rw-r--r--  1 razonyang razonyang   17 Apr 10 04:25 2.md
-rw-r--r--  1 razonyang razonyang   17 Apr 10 04:25 3.md
-rw-r--r--  1 razonyang razonyang   17 Apr 10 04:25 4.md
-rw-r--r--  1 razonyang razonyang   17 Apr 10 04:25 5.md
-rw-r--r--  1 razonyang razonyang   17 Apr 10 04:25 6.md
-rw-r--r--  1 razonyang razonyang  139 Apr  6 01:55 _index.md
-rw-r--r--  1 razonyang razonyang  141 Apr  6 01:55 _index.zh-hans.md
drwxr-xr-x  4 razonyang razonyang 4096 Apr  1 13:18 installation
drwxr-xr-x  2 razonyang razonyang 4096 Apr  1 13:18 introduction
```

It should work. 

![image](https://user-images.githubusercontent.com/17720932/230794991-cb1d350b-b883-43ae-b32d-563eda12a321.png)

**Comment by razonyang** [comment]
A clue is that please make sure there is no `index.md` (leaf bundle) in the folder, otherwise the other content are not considering as regular pages. i.e.

```
/content/docs/subfolder
---- index.md
---- a.md
---- b.md
---- c.md
---- d.md
```

The example above shows the there is one page of subfolder, the `a-d` is page resources of the page `subfolder`, if you want to make `a-b` to become regular pages, remove the `index.md` should work.

If the problem persists and more information needs to be provided, it would be better to provide a public repo for reproducing.

**Comment by keybasegit** [comment]
![Screenshot_2023-04-10-17-13-59_1920x1080](https://user-images.githubusercontent.com/83376558/230947088-e7920eb9-2d2c-49a8-836c-177acfb4a303.png)
![Screenshot_2023-04-10-17-14-38_1920x1080](https://user-images.githubusercontent.com/83376558/230947092-f126fd58-4d54-4d06-90aa-d8487e5f3c30.png)
![Screenshot_2023-04-10-17-19-12_1920x1080](https://user-images.githubusercontent.com/83376558/230947096-4e04202b-cd74-4a4d-a77d-6bec49a8ed4d.png)

Thanks for your help. Issue solved @keybasegit
