### ISSUE TITLE
chore: hb-theme.hugomods.com: correct invalid html

### ISSUE THREAD

**Issue by deining** [hbstack/theme#28]
**Check of theme example site with [W3C validation service](https://validator.w3.org/nu/?doc=https%3A%2F%2Fhb-theme.hugomods.com%2Fen%2F):**

Two errors are reported:

```
The itemprop attribute was specified, but the element is not a property of any item.
```

Were great if this error (and maybe also the warnings) could be fixed.

**Comment by razonyang** [comment]
Fixed, thank you.
