### ISSUE TITLE
Digital garden 

### ISSUE THREAD

**Issue by stardoom4** [hbstack/theme#383]
How do I create a digital garden with this theme ?

**Comment by razonyang** [comment]
The theme/template ships with some examples, i.e. https://theme.hbstack.dev/en/docs/, not sure if it meets your needs.

**Comment by stardoom4** [comment]
It may work as a Digital Garden, thanks for suggestion.

**Comment by razonyang** [comment]
You can also use that layout on whatever sections other than `docs`, i.e. `notes`, `tutorials` and so on, you just need to specify the `type` as `docs` in front matter. Take `content/notes/hello/index.md` as an example.

```markdown
---
title: Hello world
type: docs
---

CONTENT.
```
