### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by geekswg** [hbstack/theme#54]
npm run dev
时报错
PS E:\projects\blog\blog-hb\themes\geek-hb> npm run dev                                                   
> dev
> hugo server --gc --disableFastRender --enableGitInfo -D

WARN 2023/04/19 17:19:26 Module "github.com/hbstack/hb" is not compatible with this Hugo version; run "hugo mod graph" for more information.
WARN 2023/04/19 17:19:26 Module "github.com/hbstack/carousel" is not compatible with this Hugo version; run "hugo mod graph" for more information.
WARN 2023/04/19 17:19:26 Module "github.com/hugomods/images" is not compatible with this Hugo version; run "hugo mod graph" for more information.
WARN 2023/04/19 17:19:26 Module "github.com/hbstack/content-panel" is not compatible with this Hugo version; run "hugo mod graph" for more information.
WARN 2023/04/19 17:19:26 Module "github.com/hugomods/search" is not compatible with this Hugo version; run "hugo mod graph" for more information.
Error: add site dependencies: load resources: loading templates: "C:\Users\geeks\AppData\Local\Temp\hugo_cache\modules\filecache\modules\pkg\mod\github.com\hugomods\images@v0.5.1\layouts\partials\images\image.html:16:1": parse failed: template: partials/images/image.html:16: function "page" not defined

**Comment by razonyang** [comment]
> is not compatible with this Hugo version

需要安装最新的扩展版 Hugo `v0.111.3`。
