### ISSUE TITLE
Docs appearing in front page.

### ISSUE THREAD

**Issue by stardoom4** [hbstack/theme#575]
Is it possible for the Docs articles to not appear in the front page where all blog posts are shown.

**Comment by razonyang** [comment]
Are you mean the default homepage? If so, just remove the `docs` from the `hb.blog.home.sections`, then the posts on `docs` section won't be shown in the homepage.

https://github.com/hbstack/theme/blob/676d256790f77cf887849a689948881e96e81831/config/_default/params.yaml#L55-L59

**Comment by stardoom4** [comment]
Yes it worked. Thanks for the help.

**Comment by razonyang** [comment]
You're welcome.
