### ISSUE TITLE
文章预计阅读时间是在哪里设置的啊

### ISSUE THREAD

**Issue by brainstormyyf** [hbstack/theme#721]
你好，我阅读了您的文章，使用了您的HB Framework搭建了自己的博客https://yaoyifeng.top ,我自己搭建的博客网站文章预计阅读时间这个地方只有两个点，中间并没有预计时间，我不知道是改了哪里改出bug了，我想问一下这个预计阅读时间是在哪里设置的啊，非常感谢

**Comment by razonyang** [comment]
> brand 的艺术字效果

文档站点的 brand 只是用了其他字体，以 `Agbalumo` 字体作为例子：
1. 设置 [Google Web 字体](https://zh-hans.hbstack.dev/modules/look-and-feel/google-fonts/)
2. 然后添加[自定义样式](https://zh-hans.hbstack.dev/docs/advanced/style/)：
```scss
.navbar-brand {
  font-family: Agbalumo, sans-serif;
}
```

> 预计阅读时间是在哪里设置

无需设置的，这情况大概率是缺少国际化支持，建议将语言代码 `zh-cn` 改成 `zh-hans`，https://github.com/search?q=repo%3Abrainstormyyf%2Fblogsource%20%20zh-ch&type=code.
因为中文只有 `zh-hans` 和 `zh-hant` 支持本地化，比如日期的年月日，星期几等等。

**Comment by brainstormyyf** [comment]
好的非常感谢！我这就去试试！
